version: '3.7'

services:
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ygc_client
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - '3000:3000'
    restart: always
    networks:
      - ygc_network
    depends_on:
      - server
      - db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ygc_server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=5000
      - DATABASE_NAME=yougocomm
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=yougocomm123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - '5000:5000'
    networks:
      - ygc_network
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12.3
    container_name: ygc_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=yougocomm123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=yougocomm
    networks:
      - ygc_network
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - '5432:5432'

networks:
  ygc_network:
    driver: bridge

volumes:
  psql:
