version: '3.8'

services:
  ygc_client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ygc_client_container
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - '3000:3000'
    restart: always
    networks:
      - ygc_network

  ygc_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ygc_server_container
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - '5000:5000'
    networks:
      - ygc_network

networks:
  ygc_network:
    driver: bridge
