export const GET_USER = 'GET_USER';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const USER_INCOMPLETE_DETAILS = 'USER_INCOMPLETE_DETAILS';
export const USER_COMPLETED_DETAILS = 'USER_COMPLETED_DETAILS';
